# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff9d9f77f5200b77602cd29f133c42bf71db836f37c5efe47c8ce1ec77e9cc32870065d3de0ab421c3569b446fe062115afed94b46970b9e2042a06925e90eb2

test:
  secret_key_base: fa3f5e5b44f583999a2e0caee1f7711321bc7d7f5791bd7cff933ea56adb463bdaea3af639f740f50a26341c7b2e0d457736a01cf8908a72217c754eba27d86c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
